In [27]:
from scripts.utils.utils import load_json
import pandas as pd
import numpy as np
from scripts.pruning_models.classification import apply_models
from scripts.pruning_models.model import calculate_reward_transition_matrices_new
from scripts.utils.utils import load_yaml

In [2]:
networks = load_json('../data/test/networks/networks.json')
df = pd.read_parquet('../data/test/preselection/preselection.parquet.gzip')
#df_old=pd.read_parquet('/home/gezerli/Desktop/projects/reward_networks/data/exp1/preselection/preselection.parquet.gzip')
df_deneme = pd.read_parquet('../data/deneme/preselection/preselection.parquet.gzip')
params=load_yaml('../params/test/deneme.yml')

In [3]:
df_deneme

index Network_ID  Starting_Node             Preselection       Q
0      0       42_0              2     Just without outlier  blabla
1      1       42_4              1     Just without outlier  blabla
2      2       42_0              2  Non Trivial 4 / Nodes 4  blabla

In [5]:
df_nam=apply_models(networks,**params)

In [24]:
df_nam['Q'][0][0]

array([[-100.,   20.],
       [ 140.,  140.],
       [ -20.,  -20.],
       [ 140.,  -20.],
       [-100., -100.],
       [  20.,   20.]])

In [51]:
T,R=calculate_reward_transition_matrices_new(networks[2],6)


In [52]:
T[0]

array([[0., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 1.]])

In [53]:
R

array([[ -20.,  140.],
       [-100.,  140.],
       [ 140., -100.],
       [-100.,  -20.],
       [ -20.,   20.],
       [  20.,   20.]])

In [55]:
networks[2]

{'type': 'network',
 'version': 'four-rewards-v2',
 'network_id': '42_2',
 'actions': [{'reward': 140, 'sourceId': 0, 'targetId': 5},
  {'reward': -20, 'sourceId': 0, 'targetId': 1},
  {'reward': 20, 'sourceId': 5, 'targetId': 0},
  {'reward': 20, 'sourceId': 5, 'targetId': 4},
  {'reward': 140, 'sourceId': 1, 'targetId': 5},
  {'reward': -100, 'sourceId': 1, 'targetId': 2},
  {'reward': 140, 'sourceId': 2, 'targetId': 4},
  {'reward': -100, 'sourceId': 2, 'targetId': 5},
  {'reward': -20, 'sourceId': 4, 'targetId': 0},
  {'reward': 20, 'sourceId': 4, 'targetId': 3},
  {'reward': -100, 'sourceId': 3, 'targetId': 0},
  {'reward': -20, 'sourceId': 3, 'targetId': 4}],
 'nodes': [{'id': 0, 'displayName': 'A', 'x': 0.7, 'y': 0.2},
  {'id': 5, 'displayName': 'F', 'x': 0.9, 'y': 0.5},
  {'id': 1, 'displayName': 'B', 'x': 0.3, 'y': 0.2},
  {'id': 2, 'displayName': 'C', 'x': 0.1, 'y': 0.5},
  {'id': 4, 'displayName': 'E', 'x': 0.7, 'y': 0.8},
  {'id': 3, 'displayName': 'D', 'x': 0.3, 'y': 0.8}]